import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/navigation/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className + " bg-black overflow-x-hidden"}>
        <div className='max-w-screen !overflow-hidden '>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
