name: Copy Files to EC2

on:
  push:
    branches:
      - main  # Change to your repository's main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        mkdir -p $HOME/.ssh
        ssh-keyscan -H $EC2_HOSTNAME >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOSTNAME: ${{ secrets.HOST }}
    - name: Copy files via SSH
      run: |
        ssh -i ssh_key.pem ec2-user@$EC2_HOSTNAME "rm -r ~/dndaiFrontEnd-Backup/*"
        ssh -i ssh_key.pem ec2-user@$EC2_HOSTNAME "cp -r ~/dndaiFrontEnd/* ~/dndaiFrontEnd-Backup"
        ssh -i ssh_key.pem ec2-user@$EC2_HOSTNAME "rm -r ~/dndaiFrontEnd/*"
        scp -i ssh_key.pem -r ${GITHUB_WORKSPACE}/* ec2-user@$EC2_HOSTNAME:~/dndaiFrontEnd/
      env:
        EC2_HOSTNAME: ${{ secrets.HOST }}        
    - name: Npm install
      run: |
        ssh -i ssh_key.pem ec2-user@$EC2_HOSTNAME "cd ~/dndaiFrontEnd && npm install"
      env:
        EC2_HOSTNAME: ${{ secrets.HOST }}
    - name: Restarting server
      run: |
        ssh -i ssh_key.pem ec2-user@$EC2_HOSTNAME "cd ~/dndaiFrontEnd && pm2 start app.js --name frontend"
      env:
        EC2_HOSTNAME: ${{ secrets.HOST }}
  